### PR TITLE
Use standards.oftrust.net

### PR DESCRIPTION
**Pull request by soderluk**
Add CNAME record to travis config
Change all context URLs and prefixes to point to standards.oftrust.net instead of platformoftrust.github.io

### CODE REVIEW

**Review by lietu — APPROVED** [review]
Do we need a simultaneous PR for some of the APIs or similar?

**Comment by soderluk** [comment]
@lietu: Probably best. I don't know how GH-pages will react when we add the custom domain in the settings. Does the old long URL still work?

**Comment by lietu** [comment]
@soderluk as far as I know, no the old URL does not work, you can try it with the docs repo

**Comment by soderluk** [comment]
Accessing https://platformoftrust.github.io/docs/ redirects to docs.oftrust.net. :+1:

**Review by edanchenkov — APPROVED** [review]

**Pull request merged**
