### PR TITLE
Identities and links moved

### PR DESCRIPTION
**Pull request by RomanSavran**
Identities and Links contexts moved to Identity and Link subdirectories respectively

### CODE REVIEW

**Comment by RomanSavran** [comment]
According to https://dev.azure.com/DLIOy/Platform%20of%20Trust/_workitems/edit/908 urgent request

**Review by soderluk — APPROVED** [review]
LGTM

**Comment by soderluk** [comment]
@RomanSavran No changes to paths in class definitions or contexts?

**Comment by RomanSavran** [comment]
I changed only context links because this is required for some tool to understand if it is Link or Identity. I did not change urls for class definition or vocabulary to not mess with references

**Pull request merged**
